services:

  api:
    build:
      context: .
      dockerfile: src/PartnerIntegration.Api/Dockerfile

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development

      PartnerVerification__BaseUrl: http://localhost:8080

      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      RabbitMq__QueueName: partner-transactions

      Security__ApiKey: ${SECURITY_API_KEY}

    depends_on:
      rabbitmq:
        condition: service_healthy


  rabbitmq:
    image: rabbitmq:management

    hostname: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]

      interval: 5s
      timeout: 5s
      retries: 10